### ISSUE TITLE
Fairness Threshold numbers

### ISSUE THREAD

**Issue by Sreeparna1** [mas-veritas2/veritastool#12]
In https://github.com/mas-veritas2/veritastool#readme explanation, fairness threshold in the code given 0.43. but in the diagram its mentioned 0.166. how?

**Comment by mas-veritas2** [comment]
fair_threshold is an compulsory user input field while initializing use case object (CS or CM). the threshold presented in the widget is the final threshold that is used in computation. if set fair_threshold > 1, then p% rule is used, i.e. final threshold = fair_threshold/100 * perf_metric_value_of_priviledged; if if set fair_threshold to be (0, 1], then final threshold = fair_threshold
