### ISSUE TITLE
Fairness measure with only Privileged and Unprivileged

### ISSUE THREAD

**Issue by Sreeparna1** [mas-veritas2/veritastool#13]
Please provide multiclass option for features. We have only Privileged and Unprivileged groups. Example age. Age can have more than 2 groups. And we should be able to measure fairness with all these groups.

**Comment by mas-veritas2** [comment]
user needs to separate the values of a protected variables to privileged and unprivileged groups in ver 1.0. it's the same treatment implemented in other popular libraries like AIF360. supporting parities or ratios between multiple pairs will be supported in ver 2.0 with additional user input on selection policy, i.e. if there are 3 values of a protected variable, A, B and C, then which pair to be evaluated, A vs B, A vs C, A vs B+C, A + B vs C, etc
