### ISSUE TITLE
Trade-off Analysis Explanation

### ISSUE THREAD

**Issue by Sreeparna1** [mas-veritas2/veritastool#14]
Please provide the methodology and explanation for Trade off analysis. What are these 3 options and how to use it?

**Comment by mas-veritas2** [comment]
the methodology and explanation is available in phase 1 white paper @ https://www.mas.gov.sg/-/media/MAS/News/Media-Releases/2021/Veritas-Document-2-FEAT-Fairness-Principles-Assessment-Case-Studies.pdf.

can you elaborate on "3 options"? not sure what you referred to.
