### ISSUE TITLE
Trade-Off Analysis - Performance Metrics 

### ISSUE THREAD

**Issue by Sreeparna1** [mas-veritas2/veritastool#15]
For Trade-Off analysis, only balanced_acc or F1 score is available. Can we get other options? It actually should reflect the  performance metric that is set in the CreditScoring() function under the Perf_metric_name and others.

**Comment by mas-veritas2** [comment]
for trade-off analysis, the design is to use performance metrics that are not monotonically changes when threshold increases. so we included balanced_acc and F1 score only.
when perf_metric_name is not one of the above two, the primary performance metric is overridden to balanced_acc.
