### ISSUE TITLE
Trade-off performance approximation

### ISSUE THREAD

**Issue by Sreeparna1** [mas-veritas2/veritastool#16]
In trade-off analysis, consistently we are seeing the performance is better with dropping the variable. We understand that this is approximation. However, the decision will be based on these values. Please let us know the model details(computations/approximations details) here. We are not able to match the numbers with our analysis.

**Comment by mas-veritas2** [comment]
trade-off analysis uses linear interpolation to compute the metric values at each node of a 500x500 mesh grid for computation speed. e.g. for TPR, we run roc_curve to compute TPR values, then run interp1d to build a function TPR(threshold) to make O(1) for obtaining metric value at each grid node. please refer to the source code for full implementation.
