### ISSUE TITLE
Feature Importance

### ISSUE THREAD

**Issue by Sreeparna1** [mas-veritas2/veritastool#17]
More explanation needed on Feature_importance() function. We are unable to understand why the fairness measure will change to find the feature importance. 
Also, the fairness conclusion is not tallying with the result in the attached file(chosen Threshold is 80). 
![Feature_Imp](https://user-images.githubusercontent.com/93760849/140475442-09a17d01-f50d-4c48-80a5-1c1b93c77e9e.JPG)

**Comment by mas-veritas2** [comment]
we use leave-one-covariate-out to justify the use of protected variables (refer to phase 1 https://www.mas.gov.sg/-/media/MAS/News/Media-Releases/2021/Veritas-Document-2-FEAT-Fairness-Principles-Assessment-Case-Studies.pdf)

e.g. after removing SEX, we retrain the model and measure the prediction to see how balanced_acc and equal_opp changes compared to the original model.

widget shows the fairness conclusion for the original model. the "fair conclusion" column in the output of Feature_importance() shows the change of conclusion, i.e. the term before "to" is for original model and the term after is for retrained model, e.g. "fair to unfair" means original model is fair and retrained model is unfair.
