### ISSUE TITLE
Overall API 

### ISSUE THREAD

**Issue by Sreeparna1** [mas-veritas2/veritastool#18]
The API site, https://htmlpreview.github.io/?https://github.com/mas-veritas2/veritastool/blob/master/veritastool/resources/specs/API_Specs_final.htm#_Toc85640077 needs more methodology explanation and the explanation of how to use the results with examples.

**Comment by mas-veritas2** [comment]
noted. we will put the reference to phase 1 white paper.
for explanation on how to use, we will add the notes to tutorial notebooks.
