### ISSUE TITLE
Application of CreditScoring()

### ISSUE THREAD

**Issue by LIFENGZI1015** [mas-veritas2/veritastool#20]
Can we use CreditScoring() for a general binary classification, even it is not exactly a credit scoring use case?

**Comment by mas-veritas2** [comment]
yes, you can use it by omitting inputs for rejection inference. if you wanna use fairness metric suggestion, please note that positive label of dataset is fixed to "favorable" (for Q1 in Veritas Fairness Tree). so you need to check if it is aligned with your use case.

**Comment by LIFENGZI1015** [comment]
This is related to my previous question of "pos_label setting in ModelContainer()" #22, Veritas internal encoding will automatically make positive label as 'favorable', we also provide inputs to fair_concern='inclusive', fair_priority='harm' and fair_impact='normal', so the fairness metric suggestion shall be sensible. Is that correct?

**Comment by mas-veritas2** [comment]
internal encoding is to transform a unifying format to facilitate downstream computation. e.g. class labels {"Yes", "No"} in the provided dataset. Treating positive label as favorable is a setting of "credit scoring" use case. 4 questions to be answered in Veritas Fairness Tree. we fixed the answer for Q1 for each use case, and let user specify the answers for Q2 to Q4.

**Comment by LIFENGZI1015** [comment]
That's clear. Thanks.
