### ISSUE TITLE
Fairness Evaluation on Multi-class classification

### ISSUE THREAD

**Issue by LIFENGZI1015** [mas-veritas2/veritastool#21]
How can we apply the Veritas fairness assessment on a multi-class classification problem?

**Comment by mas-veritas2** [comment]
for multi-class classification, you can separate the classes to two groups and assign them to pos_label and neg_label respectively. it effectively transforms multi-class problems to binary problems. it is the same approach that AIF360 takes for multi-class classifications. in ver 2.0, we will support metric computation among multi-class with different policies, e.g. major vs the rest, worse case, etc.

**Comment by LIFENGZI1015** [comment]
Thanks. It is clear. Look for the ver 2.0.
