### ISSUE TITLE
pos_label setting in ModelContainer()

### ISSUE THREAD

**Issue by LIFENGZI1015** [mas-veritas2/veritastool#22]
In ModelContainer(), pos_label was set as [[0]] in our project, meaning that favorable label is 0. 

But it seems to be contradicting with requirements in API document (https://htmlpreview.github.io/?https://github.com/mas-veritas2/veritastool/blob/main/veritastool/resources/specs/API_Specs_final.htm#_Toc85640078), saying that “For all classification model types except uplift, converts the favorable labels to 1 and others to 0.”. Please clarify this.

**Comment by mas-veritas2** [comment]
the above-mentioned text refers to the internal encoding for class labels. in your example, the library will encode class label "0" in your dataset as "1" and encode the rest of class labels as "0" prior to fairness diagnosis computations.

**Comment by LIFENGZI1015** [comment]
This is clear. So as long as we provide the correct input for pos_label, Veritas library will automatically convert to have positive value being favorable. Thanks.

**Comment by mas-veritas2** [comment]
there's some confusion here. pos_label might not be favorable always, depending on use case. pos_label is considered favorable for credit scoring; but it is unfavorable for marketing rejection model ("1" means rejected by underwriting). we will improve the document for clarity.

**Comment by LIFENGZI1015** [comment]
Q1. Yes, label "1" has different meanings for various use cases. For our case, client attrition, after conversion, "1" represents favorable (no attrition) and "0" represents unfavorable (attrition). Our focus is on "0" for intervention, so we provide fair_concern = 'inclusive', fair_priority='harm' and fair_impact='normal'. Please confirm if this is the use case, the fairness assessment conclusion should make sense. 

Q2. I noticed that after label encoding conversion ("1" as favorable), all the subsequent results, e.g. Class Distribution, are calculated based on the converted labels, , is it correct?

**Comment by mas-veritas2** [comment]
Q1. it is right to use credit scoring use case and set fair_concern = 'inclusive'
Q2. yes, computed w.r.t. the favored label.
