### ISSUE TITLE
Protected variable not used in model training

### ISSUE THREAD

**Issue by LIFENGZI1015** [mas-veritas2/veritastool#23]
Protected variable (Group 1 variables based on Phase 2 white paper) is not used in model training, but they are included in x_train and x_test. 

Please clarify the above setting is correct and fairness.evaluate() will calculated based on y inputs, while x inputs will be used in feature_importance when using LOO?

**Comment by mas-veritas2** [comment]
1. protected variables (protected_features_cols) are not necessary to be included in model training.
2. fairness.evaluate() will calculated based on y inputs as well as the row-wise masks derived from protected variables.
3. if protected_features_cols are not provided, it will be filled with x_test
4. x inputs are used for feature_importance (LOO and correlation)

**Comment by LIFENGZI1015** [comment]
In our case:
1. Protected variable refers to (p_var). It is not used in model training.
2. But p_var are included in x_train and x_test together with other features for model training.

Q1. What are the differences between p_var and protected_features_cols.
Q2: Can you briefly explain how protected_features_cols do row-wise masking.

**Comment by mas-veritas2** [comment]
Q1
p_var is an array of names of protected variables;
protected_features_cols is a dataframe with column name = p_var
if protected_features_cols is not provided, then protected_features_cols = x_test[p_var]

Q2
if privileged group is  {'Sex': 1}, then masking for Sex is "mask = protected_features_cols['Sex'] == 1".
e.g. TPR parity = TPR(y_true[mask], y_pred[mask]) -  TPR(y_true[~mask], y_pred[~mask])

**Comment by LIFENGZI1015** [comment]
It's clear. Thanks.

**Comment by LIFENGZI1015** [comment]
A follow-up question is: If we have more than 1 disadvantage groups, the TPR parity will be calculated for each disadvantage group vs the privileged group and select the WORST TPR parity to check the fairness using 80% rule, is that correct?

**Comment by mas-veritas2** [comment]
no, privileged vs unprivileged is a binary treatment in 1.0 (i.e. transforming protected variables to be binary-valued). so you need to run the diagnosis twice and subset your dataset to keep one disadvantage group each time. in 2.0, the toolkit will support multi-valued protected variables and support "worse case policy" to compute the worst values of a fairness metric among all pairs.

**Comment by LIFENGZI1015** [comment]
Got it. This is clear. Look forward to version 2.0 which is catering for more scenarios. We can close this for now.
