### ISSUE TITLE
Package versioning issues

### ISSUE THREAD

**Issue by LIFENGZI1015** [mas-veritas2/veritastool#24]
Our blank model object is using GradientBoostingClassifier from sklearn.ensemble, the version is 0.20.3, while in Veritas diagnosis tool requirements, the version is 0.24.2, how to solve the versioning issues.

**Comment by mas-veritas2** [comment]
you can use "pip install -c constraint.txt" and put "scikit-learn == 0.20.3". but you will get import error as "sklearn.metrics.mean_absolute_percentage_error" is available from 0.24 onwards.

**Comment by LIFENGZI1015** [comment]
Thanks for the response. It is clear.
