### ISSUE TITLE
Future Enhancement for Time series problem

### ISSUE THREAD

**Issue by LIFENGZI1015** [mas-veritas2/veritastool#25]
When will we get the Veritas fairness libraries for time series problems or regression problems?

**Comment by mas-veritas2** [comment]
ver 2.0 will support regression use case.

**Comment by LIFENGZI1015** [comment]
Do you have any tentative timeline for this? Thanks.

**Comment by mas-veritas2** [comment]
generally time series model can use generic regression use case to be built in 2.0

**Comment by LIFENGZI1015** [comment]
Thanks for the update. Good to know that. We want to know a proposed time for 2.0, mid next year?

**Comment by mas-veritas2** [comment]
tentative plan is Apr to Sep 2022, subject to funding approval.

**Comment by LIFENGZI1015** [comment]
Noted with thanks.
