### ISSUE TITLE
Fairness threshold

### ISSUE THREAD

**Issue by LIFENGZI1015** [mas-veritas2/veritastool#26]
In Fairness evaluate results, Fairness threshold is shifted down by 1. In our use case, it is 0.123 so the original threshold should be 1.123, which is not consistent with fair_threshold = 80 in CreditScoring() as it should be 1.2. Please clarify.

![Screenshot (301)](https://user-images.githubusercontent.com/64296675/142721002-d590550e-bee5-494d-a53f-33b1a49287ca.png)

**Comment by mas-veritas2** [comment]
the footnote explains that "shift down by 1" is only for ratio-based metrics in the chart. for all metrics in the chart, only "demographic impact" is ratio-based, marked by "*". "0.123" is not relevant here, because 1) it's not in the chart; 2) it's for FPR parity, not a ratio-based metric.

**Comment by LIFENGZI1015** [comment]
The only ratio-based metric is Disparate Impact (I believe it is a typo in you response).
It is still not clear on how Threshold of '0.123' is calculated and what is the 'Threshold Range' indicated in the chart. 
It is not straightforward for users to understand how to check fairness metrics against the 80% rule. It's not illustrated clearly on this visualization widget.

**Comment by mas-veritas2** [comment]
- while user sets 80 as fair_threshold (i.e. 80% rule), internally the threshold (0.123 in your case) is computed by "performance_metric of privileged group * (1 - 80%)".
- the "Threshold Range" in the chart is from -0.123 to +0.123.
- yes, you are right about Disparate Impact. sorry for my typo.

**Comment by LIFENGZI1015** [comment]
Thanks. It is clear now. 

But suggest to give the ratio based results as well, as it is not straightforward when users try to check against 80% rule which is ratio-based intuitively.

**Comment by mas-veritas2** [comment]
noted. we will include ratio version in 2.0.

**Comment by LIFENGZI1015** [comment]
Thanks and we can close this.
