### ISSUE TITLE
trade-off analysis

### ISSUE THREAD

**Issue by LIFENGZI1015** [mas-veritas2/veritastool#27]
Q1. Does ‘separated thresholds’ under Neutral Fairness' mean the primary fairness metric False Positive Rate Ratio is 1 (or fairness metric False Positive Parity is 0 though it is shown as 0.001)?

![Capture](https://user-images.githubusercontent.com/64296675/144200902-4acf524b-254a-42bd-b2a1-55164a24c31b.PNG)

Q2. Purple Marker is not shown in the figure after it is uploaded and shown on assessment tool.

![Capture2](https://user-images.githubusercontent.com/64296675/144202292-2abb090a-a211-469f-af59-cfa5a508e7e2.PNG)

**Comment by mas-veritas2** [comment]
Q1. "separated thresholds under Neutral Fairness" means to limit the value of primary fairness metric within +/- 0.001 delta range. we will refine the description to avoid confusion
Q2. could you email us the json file for further investigation?

**Comment by LIFENGZI1015** [comment]
Q1. noted.
Q2. Sorry we are not able to provide the model artifacts as it contains our internal use case data/results.

**Comment by mas-veritas2** [comment]
noted. then we will investigate further during code maintenance and close this issue for now.
