### ISSUE TITLE
Feature_importance and auto-generated answer in assessment tool

### ISSUE THREAD

**Issue by LIFENGZI1015** [mas-veritas2/veritastool#28]
In our case, protected variable is not used in model training. From the LOCO analysis we have the results and auto-generated answer in the assessment tool.

Q1. 'baseline model' refer to our original fairness results or a newly trained model (we provide model in Model Wrapper) that uses all features provided even the protected variable?

Q2. it is confusing to have the auto-generated answer for our case, as we dont include that in the beginning. 

![Capture3](https://user-images.githubusercontent.com/64296675/144205575-67f278f0-dc53-47d8-b8e5-7de5ae4b0a16.PNG)

**Comment by mas-veritas2** [comment]
Q1. 'baseline model' refers to the original model producing y_test or y_prob.
Q2. auto-generated answers can be deleted easily if you do not like them. furthermore, it would be great if you could highlight to the developer team (BOC) on what improvement you would like to see for auto-generated answers.

**Comment by LIFENGZI1015** [comment]
Follow-up question on the LOCO analysis, as the protected variable is not included in the original model training so what does LOCO produce here as we already leave the protected variable out? Could you clarify this?

**Comment by mas-veritas2** [comment]
it's to remove protected variable from x_train and x_test, call the given model fitting function to rebuilt the model and finally score it on x_test.

**Comment by LIFENGZI1015** [comment]
yes, understood. In our case, original model and the LOCO rebuilt model are both trained with protected variable being dropped. In theory, fairness metrics shall be the same (as features are the same). But the results are different now. Reasons could be we are using different model package versions due to in-combability of versions or versions of inputs. 

In order to properly use LOCO, protected variable shall be included in the original model and then LOCO will drop the protected variable and compare the fairness metrics.

**Comment by mas-veritas2** [comment]
yes, agreed. for the difference, you may check if random seed is required assuming data inputs are the same. as the toolkit just provides a function wrapper for fitting the model, i would close this issue for now.
