### ISSUE TITLE
Clarification on fairness metrics reports 

### ISSUE THREAD

**Issue by jeannefukumaru** [mas-veritas2/veritastool#29]
Hi! 

Thanks for this package. I'm currently exploring it since my company, Databricks, has FSI customers. May I please ask:

1. What is the base group used for the parity measures please? 
2. How are "privileged" and "unprivileged" groups defined? 
3. For the tradeoff report, when I extract the `tradeoff_obj`, how are the values supposed to connect to the report that is printed to screen? (see screenshot) 
4. Lastly, for large datasets that would not fit into the `ModelContainer` object, do you have recommendations on how to obtain a fairness assessment? 

Thanks in advance!

**Comment by nisithsinghAAI** [comment]
Hi, 
Thanks for your questions.

1. Base group used for parity measures is the privileged group.
2. Privileged group is the cohort receiving a preferential outcome comprated to the unprivileged froup
3. The tradeoff results printed to screen by diagnosis tool are only for the max performance cases. Although the Fairness.get_tradeoff_results() API function (Refer to API specs) contains the values for all other cases. Please reattach screenshot.
4. For large datasets, you can pass the x_train and x_test as string paths where the datasets reside. Then use the ModelWrapper to load the dataset for any training required during the fairness assessment. At a minimum, if x_train and x_test are string paths, the protected_features_cols parameter during the ModelContainer initialization. These are the protected feature columns from the x_test.
