### ISSUE TITLE
Test Function Failed

### ISSUE THREAD

**Issue by JeromeWYCB** [mas-veritas2/veritastool#30]
1. The test function failed. The differences between the result and sample are negligible. Is this the expected behavior?

![image](https://user-images.githubusercontent.com/37611437/208828302-c92f323b-68db-4d70-9f6e-947e4c9f9667.png)

**Difference 1: ROC AUC**
![image](https://user-images.githubusercontent.com/37611437/208828935-a9358b12-300d-40f8-b050-1d1f2db0f939.png)

**Difference 2: MI Separation**
![image](https://user-images.githubusercontent.com/37611437/208829532-c8a7f712-0da1-4cf5-b74b-04e7312efba7.png)

**Difference 3: AUC and Log Loss Parity**
![image](https://user-images.githubusercontent.com/37611437/208829815-de3050c6-2911-44ec-aac4-20c4997e00bc.png)

**Comment by mas-veritas2** [comment]
Yes, it’s negligible.
