### ISSUE TITLE
Incorrect denominator for disparate_impact

### ISSUE THREAD

**Issue by michaelchia** [mas-veritas2/veritastool#33]
disparate_impact calculates the ratio as pr_p/pr_u. However, the ratio threshold logic checks abs(ratio-1)>(1-threshold/100). For it to be consistent with the parity threshold logic (abs(parity)>(1-threshold/100)*priv), the ratio should be pr_u/pr_p. Else even though demographic_parity and disparate_impact are variations of the same metric, they would both produce different conclusions.

If intentional, kindly explain the rationale.

https://github.com/mas-veritas2/veritastool/blob/1a7dc4f3d2c4e5bd435b5270c846c417f8656c32/veritastool/metrics/fairness_metrics.py#L363-L387

**Comment by mas-veritas2** [comment]
Noted. Dev team will look into it.

**Comment by nisithsinghAAI** [comment]
This has been fixed.
