### ISSUE TITLE
Incorrect privileged metric value for calibration_by_group 

### ISSUE THREAD

**Issue by michaelchia** [mas-veritas2/veritastool#34]
The priv_m_v for calibration_by_group is (ppv_p-ppv_u)/2. It should be (ppv_p+for_p)/2. Similar to equalized_odds.

https://github.com/mas-veritas2/veritastool/blob/1a7dc4f3d2c4e5bd435b5270c846c417f8656c32/veritastool/metrics/fairness_metrics.py#L846-L874

**Comment by mas-veritas2** [comment]
Noted. It has been fixed in ver 2.0. thanks for pointing it out.
