### ISSUE TITLE
Calculation bug in mi_separation

### ISSUE THREAD

**Issue by michaelchia** [mas-veritas2/veritastool#41]
https://github.com/mas-veritas2/veritastool/blob/b1d2384f10ebd7da13ab88a5c9999c5fe6b1d1fd/veritastool/metrics/fairness_metrics.py#L1703-L1722

line 1717 is:
`e_y_pred_curr_p_var = self._get_entropy(df,['y_pred', 'curr_p_var'])`
However, i believe it should be:
`e_y_true_y_pred = self._get_entropy(df,['y_true', 'y_pred'])`
And of course changing the correspond variable in 1721 from e_y_pred_curr_p_var to e_y_true_y_pred, and modifying the optimised version of the function accordingly.

mi_separation and mi_sufficiency should be similar except swapping y_pred and y_true. Line 1717 breaks the symmetry.

And testing empirically with independently random y_true, y_pred and curr_p_var, where curr_p_var is independently random but non-even groups (e.g. 1000 rows are privileged, 100 rows are unprivileged), mi_separation results in values significantly far away from zero. Where since they are all independent variables, the metric should be close to zero.

**Comment by SagarGunjal-Accenture** [comment]
Noted. Changes are made and will reflect in Version 2.0
