### ISSUE TITLE
strict versioning for dependencies

### ISSUE THREAD

**Issue by michaelchia** [mas-veritas2/veritastool#50]
Currently the requirement are using strict versioning (e.g. numpy==1.23.5). However, it is generally best practice for packages to use some from of range versioning (e.g. numpy>=1.19 or numpy~=1).

This make it easier for users to manage their dependencies so that veritastool can be used as part of a larger codebase.

I would additionally request to be generous with the version ranges. i.e. making the range as wide as possible as long as it is compatible with the package. This will allow more legacy projects to use the tool without requiring them to alter the versions of their dependencies which may require extra testing. e.g. allow for pandas>=1.0 rather than pandas>=1.5.3.

On a related sidenote, I would suggest removing development only dependencies from the requirements, namely "pytest". generally best practice is to separate the requirements for running the package itself and requirements for developers when working on the package. e.g. having a requirements.txt which is used in the setup.py and a separate requirements-dev.txt for dev packages. This will further help mitigate those "dependency hell" issues for users using veritastool.

**Comment by nisithsinghAAI** [comment]
Hi Michael, 

Thanks for sharing your concerns and valuable suggestions. 

1) The versions in the requirements.txt are only the recommended ones as they have been used for running the tests successfully on different operating systems. A different combination of versions can possibly be supported.
To determine if package versions other than those specified are supported, the tests can be run (using pytest) to check if all were successful. 

2) Currently, pytest is the only development-only dependency (required for running the test scripts) we are maintaing only one requirements.txt. In the future, if more development-only dependencies get added, we can surely include your suggestion.

**Comment by michaelchia** [comment]
hello nisith, the issue is that if strict versions are declared in the requirement.txt (or more specifically the 'install_requires' in the setup.py) and pip will treat it as ONLY those versions are compatible and pip will complain about dependency conflict if now other versions are installed as it will conflict with the requirements of veritastool. E.g. if my project has requirements like "pandas==1.0.1; veritastool==2.0.0", my pip install of that requirements file will fail due to dependency conflict. this is probably where a requirements-dev.txt can help as you can just keep your existing strict versioned requirements as requirements-dev.txt and have the ranged versioned requirements as requirements.txt (which is loaded into the 'install_requires' in the setup.py)

**Comment by mas-veritas2** [comment]
Noted. However, we have to keep current strict versioning before comprehensive testing on the relaxed versioning. We tried with ">=" approach but it turned out to break down the library. If you are aware of a list of relaxed versioning that does not break down the library, please let us know.

**Comment by michaelchia** [comment]
The issue is more to do with the testing. The data you use for the testing are stored as a pickle. The issue is that pickled objects are sensitive to package versioning. E.g. the pandas dataframes that are pickled were written using 1.5.3 so they won't be able to be read by like pandas 1.3 or 2.0.  This makes it difficult to test for different versions, both older and newer versions. It would definitely be important to be able to support the latest version of packages in case of bugfixes or new features that the user's other code requires. E.g. pandas==2.0 was just released but the test suite is unable to test for it even though it is very likely veritastool itself is compatible with pandas2.0.

So you would probably want to reconsider how you store your test data. probably best to store your data as CSV and json or perhaps write generators to generate your test data.

I have run my own tests of the code even using python3.6 and it seems to work with much lower versions of the dependencies. But of course my tests don't have comprehensive coverage so you would need to fix your test suite before safely making the dependency changes

**Comment by mas-veritas2** [comment]
python 3.6 would encounter problem with transparency function because of dependency on sklearn. 
for pickle, i agreed with you on compatibility and we will update the data storage format in future maintenance. thanks for the insights.
