### ISSUE TITLE
Incorrect calculation of equal_odds_ratio, neg_equal_odds_ratio, calibration_by_group_ratio

### ISSUE THREAD

**Issue by michaelchia** [mas-veritas2/veritastool#52]
https://github.com/mas-veritas2/veritastool/blob/aec3f5fc866c89702d6b63a9ee4ad4b176deec0f/veritastool/metrics/fairness_metrics.py#L1049-L1077

The ratio calculation in line 1071 is currently `((tpr_u + fpr_u) / (tpr_p + fpr_p))/2`. It should be `(tpr_u + fpr_u) / (tpr_p + fpr_p)`, since it the ratio is ((tpr_u + fpr_u)/2) / (tpr_p + fpr_p)/2). 

Similar for neg_equal_odds_ratio and calibration_by_group_ratio.

**Comment by mas-veritas2** [comment]
noted. we will fix it shortly. thanks for reporting this.
