### ISSUE TITLE
incorrect calculation of wape

### ISSUE THREAD

**Issue by michaelchia** [mas-veritas2/veritastool#54]
https://github.com/mas-veritas2/veritastool/blob/dcba27575ff80053744c8b23b245aa3d008c0107/veritastool/metrics/fairness_metrics.py#L1281-L1308

Currently wape calculation uses sum(y_true) as the denominator, however as per the definition, it should be sum(abs(y_true)).

line 1305 is currently 'np.sum(np.absolute(np.subtract(y_true[mask], y_pred[mask])))/ np.sum(y_true[mask])', it should be 'np.sum(np.absolute(np.subtract(y_true[mask], y_pred[mask])))/ np.sum(np.absolute(y_true[mask]))'.

Sidenote: using np.mean instead of np.sum might be slightly more resilient to a potential float overflow issue.

**Comment by michaelchia** [comment]
also it is missing the application of the sample_weight

**Comment by mas-veritas2** [comment]
noted and thanks. we will fix it.
